Experiment_name: ci/pose

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ci/train_data_bone.npy
  label_path: ./data/ci/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ci/test_data_bone.npy
  label_path: ./data/ci/test_label.pkl

# model
model: model.shift_gcn.Model
model_args:
  num_class: 10
  num_point: 36
  num_person: 1
  graph: graph.ntu_rgb_d1.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 1e-5
step: [20,40]

# training
device: [0]
only_train_epoch: 1
batch_size: 32
test_batch_size: 32
num_epoch: 50
nesterov: True
data_dir : '/home/zhenghua/two-stream-a'
dataset_dir : '/home/zhenghua/zj/dataset/CI'
Max_n : 15
Max_group_num : 105
weights: ''
dataset: ci
