work_dir: ./work_dir/bit
data_dir: /home/zhenghua/two-stream-a
dataset_dir: /home/zhenghua/zj/dataset/BIT
weight_decay: 0.01
lr: 0.00001
epoch: 100
batch_size: 3
num_class: 9
roi_size: [5,5]
bilinear_size: [60,80]
feature_size: [240,320]
num_workers: 8
max_box_num: 5
max_group_num: 10
pretrain_model: '/home/zhenghua/zj/Fusion_shift_resnet/config/bit/data_name/resnet50-20-0.9082794706063404.pt'
